### ISSUE TITLE
Jira CLOUDDST-10308: “oc” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by RiRa12621** [openshift/oc#1037]
## Reproduce
* Download CLI tool from https://console.redhat.com/openshift/install/aws/arm
* unpack archive `$ tar -xzvf openshift-client-mac.tar.gz`
* move file `$ sudo mv oc /usr/local/bin/oc`
* execute `oc` command like `$ oc get pods`

## Expected behaviour:
`oc` commands allow interaction with OpenShift cluster

## Current behaviour
![Screenshot 2022-01-27 at 09 34 55](https://user-images.githubusercontent.com/14996407/151321701-f0ba46e2-7cfd-4dcd-a95c-564d028a2ce7.png)

## Environment

```
$ uname -a
Darwin MAC-FVFGH12JQ05P 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:29:10 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T8101 arm64
```

**Comment by joepvd** [comment]
Being handled here: https://issues.redhat.com/browse/CLOUDDST-10308

**Comment by RiRa12621** [comment]
/retitel Jira CLOUDDST-10308: “oc” cannot be opened because the developer cannot be verified.

Card isn't public
