### ISSUE TITLE
fish completions

### ISSUE THREAD

**Issue by RafalSkolasinski** [openshift/oc#1066]
Currently the `oc` tool provides shell completions for `bash` and `zsh`. 
It would be nice if it could include `fish` completions as well.

**Comment by reitzig** [comment]
FWIW, it's unclear to me how a contribution would work. I can't find Go sources for `oc completion` anywhere; would we add (and manually maintain) files in `contrib/completions`?

On the other hand, it seems Cobra is being used, which _does_ generate completions for fish (and also PowerShell!).

**Comment by reitzig** [comment]
/remove-lifecycle stale

A comment by a maintainer would be appreciated

**Comment by reitzig** [comment]
/remove-lifecycle rotten

A comment by a maintainer would be appreciated

**Comment by reitzig** [comment]
/close 

Seems to have been resolved in the meantime:

```fish
❯ oc version
Client Version: 4.10.0<snip>

❯ oc completion fish | head

# fish completion for oc                                   -*- shell-script -*-

function __oc_debug
    set -l file "$BASH_COMP_DEBUG_FILE"
    if test -n "$file"
        echo "$argv" >> $file
    end
end
```

Thanks!
