### ISSUE TITLE
oc-mirror support for registries.conf

### ISSUE THREAD

**Issue by joehuizenga** [openshift/oc#1163]
Hi, this is my first issue created in this repo so apologizes if not following the correct process. 

We have been working with the oc-mirror plugin and trying to adopt as it matures, one of the issues we have is that it does not support an image redirection capability similar to what skopeo does via /etc/containers/registries.conf today.  Would be great if that capability existed and was usable via oc-mirror!  We had originally opened this ticket in the oc-mirror repo for more background

https://github.com/openshift/oc-mirror/issues/356

**Comment by morstad** [comment]
Believe this is now covered under https://issues.redhat.com/browse/WRKLDS-468?page=com.docminer.jira.issue-links%3Acom.kintosoft.jira.links.tab-panel
