### ISSUE TITLE
Bring `kubectl top` to oc

### ISSUE THREAD

**Issue by kaovilai** [openshift/oc#1211]
oc IIUC is supposed to be contain all kubectl commands.
top is missing.

**Comment by ardaguclu** [comment]
Could you please check `oc adm top` command which should correspond to `kubectl top` command.
I'd prefer closing this issue, since the command already exists. Feel free to re-open it if you think I'm missing something. Thanks.

/close

**Comment by kaovilai** [comment]
/reopen

That means you simply cannot run scripts with
`alias kubectl=oc`

**Comment by kaovilai** [comment]
> as I know there is no guarantee that same command path should work in oc as the way of kubectl.

:(
