### ISSUE TITLE
oc executable issue on Mac OS ARM64 (Apple Silicon)

### ISSUE THREAD

**Issue by tkelkermans** [openshift/oc#1221]
Hello,

Tried to install oc command-line using two methods :

1. `brew install openshift-client ` (openshift-client-mac-arm64.tar.gz)
2. Downloading it from https://console.redhat.com/openshift/install/ (macOS aarch64)
In both case, when I try to use the oc command line I get the following error on Mac : "“oc” is damaged and can’t be opened. You should move it to the Bin."

It works using x86_64 and Rosetta2.
I'm using a MacBook Pro 14" M1 Pro, running Monterey 12.5

**Comment by saumets** [comment]
@tkelkermans If you use the regular formula version (`brew install openshift-cli`) it should work and install fine on arm64. It's what I'm currently using on my Macbook Pro 16.

The Homebrew `openshift-client` that you referenced is a cask version, and I've had the same issue as you with that one (damaged and can't be opened). Using the regular formula works though, but I think the client version is a little outdated (i think).

**Comment by cfergeau** [comment]
Rebuilding `oc` from source on an m1 with golang 1.17 or 1.19 also gives a working binary.

**Comment by cfergeau** [comment]
> "something" seems to be trying to set the openshift version in the macOS arm64 binary, but is buggy and is corrupting the binary in the process?

Probably related to https://github.com/openshift/oc/blob/e0f8e21d03a0fd161f02729b3679bdcbccebb1b8/pkg/cli/admin/release/extract_tools.go#L749-L768

**Comment by voxel01** [comment]
> @tkelkermans If you use the regular formula version (`brew install openshift-cli`) it should work and install fine on arm64. It's what I'm currently using on my Macbook Pro 16.
> 
> The Homebrew `openshift-client` that you referenced is a cask version, and I've had the same issue as you with that one (damaged and can't be opened). Using the regular formula works though, but I think the client version is a little outdated (i think).

Am I wrong or gives openshift-cli a very old version (4.2) instead of the advices 4.12?

`
% brew install openshift-cli
....
% oc version --client
Client Version: v4.2.0-alpha.0-1570-g3c85519
Kustomize Version: v4.5.4
`

**Comment by cfergeau** [comment]
The git hash at the end (`3c85519`) matches some much newer commits (from beginning of August). The binary corruption might be coming from code trying to replace this 4.2.0 with something more representative of the current version ;)

**Comment by cfergeau** [comment]
For the record, the command which triggers the problematic code path is
```
oc adm release extract -a $PULLSECRET --tools --command-os='*'  quay.io/openshift-release-dev/ocp-release@sha256:98c294a87ab2e794e313e2d7da8a63efcc01e3e850ad92281ae39b7e525696e6
```
(for this OpenShift release https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.11.2/release.txt )

**Comment by cfergeau** [comment]
A workaround could be:
```
diff --git a/pkg/cli/admin/release/extract_tools.go b/pkg/cli/admin/release/extract_tools.go
index d0a91ca4e..4c3581409 100644
--- a/pkg/cli/admin/release/extract_tools.go
+++ b/pkg/cli/admin/release/extract_tools.go
@@ -189,10 +189,9 @@ func (o *ExtractOptions) extractCommand(command string) error {
 			NewArch: true,
 			Mapping: extract.Mapping{Image: "cli-artifacts", From: "usr/share/openshift/mac_arm64/oc"},
 
-			LinkTo:               []string{"kubectl"},
-			Readme:               readmeCLIUnix,
-			InjectReleaseVersion: true,
-			ArchiveFormat:        "openshift-client-mac-arm64-%s.tar.gz",
+			LinkTo:        []string{"kubectl"},
+			Readme:        readmeCLIUnix,
+			ArchiveFormat: "openshift-client-mac-arm64-%s.tar.gz",
 		},
 		{
 			OS:      "linux",
@@ -256,10 +255,8 @@ func (o *ExtractOptions) extractCommand(command string) error {
 			Command: "openshift-install",
 			Mapping: extract.Mapping{Image: "installer", From: "usr/bin/openshift-install"},
 
-			Readme:               readmeInstallUnix,
-			InjectReleaseImage:   true,
-			InjectReleaseVersion: true,
-			ArchiveFormat:        "openshift-install-linux-%s.tar.gz",
+			Readme:        readmeInstallUnix,
+			ArchiveFormat: "openshift-install-linux-%s.tar.gz",
 		},
 		{
 			OS:      "linux",
```
but we'd be left with no good version numbers in `oc version` (see https://github.com/openshift/oc/issues/1221#issuecomment-1231379176 in this same issue for why this could be confusing)

**Comment by cfergeau** [comment]
All macOS M1 binaries have an 'adhoc' signature, see https://github.com/golang/go/issues/42684
If we binary patch oc executable without changing the signature, it's expected the binary won't load anymore.
Running 'codesign --force -s - oc' after downloading/unpacking it allows the binary to start.

**Comment by ingvagabund** [comment]
@cfergeau do you know whether changing the signature has become required recently? The referenced go issues was reported in 2020. I wonder whether the oc binary has not been functioning for the last 2 years. Or, whether the issue has started to manifest starting 4.10.

**Comment by cfergeau** [comment]
The golang issue says that signatures are required for arm64 binaries. The x86_64 binaries would have no such issues as they are not signed. All the arm64/M1 binaries I could test have been non-functional, the oldest one I found is https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/4.10.0/openshift-client-mac-arm64-4.10.0.tar.gz which is 6 months old.

**Comment by kenmoini** [comment]
So is there any working updated version of the oc CLI that support Apple Silicon?

**Comment by cfergeau** [comment]
Progress on this issue has been tracked in https://bugzilla.redhat.com/show_bug.cgi?id=2059125 but it's now fixed.
The x86_64 binaries have always worked (with rosetta) on Apple Silicon. When 4.12.0.ec-5 is released on https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp-dev-preview/ it should have a working arm64 binary as well.

**Comment by cgruver** [comment]
@kenmoini This workaround will fix it until we get the OOTB working binary in 4.12.

```bash
codesign --force -s - $PATH_TO_OC/oc
```

**Comment by ingvagabund** [comment]
Can anyone please check whether the latest oc releases are fixing the reported issue?

**Comment by ingvagabund** [comment]
Thank you for the conformation. Closing as resolved.
/close
