### ISSUE TITLE
oc sa get-token fails with an error "could not find" on 4.11

### ISSUE THREAD

**Issue by MatousJobanek** [openshift/oc#1225]
When running:
```
oc sa get-token default -n default
``` 
against OpenShift 4.11, then it fails with:
```
error: could not find a service account token for service account "default"
```
The reason is that the code tries to iterate over the ServiceAccount's secrets https://github.com/openshift/oc/blob/master/pkg/cli/serviceaccounts/gettoken.go#L122 but Kube 1.24 doesn't include the secrets of the type `kubernetes.io/service-account-token` in the SA's secrets.

**Comment by MatousJobanek** [comment]
never mind - didn't notice that there is the new `create token` command :facepalm:

**Comment by nate-duke** [comment]
Shouldn't this still work even in the presence  of the `create-token` sub-command or should `get-token` maybe be removed if `create-token` is the preferred method? As it is now the `get-token` sub-command simply doesn't work at all.

**Comment by akram** [comment]
I am facing a similar issue with:
```
oc sa create-kubeconfig  my-sa
error: could not find a service account token for service account
```
I guess the cause is the same
