### ISSUE TITLE
Docs missing for donwloading a pre-built `oc` binary

### ISSUE THREAD

**Issue by aliok** [openshift/oc#1247]
I just needed to upgrade my `oc` application. Quick googling forwarded me to this repo but I couldn't find a binary listed anywhere in the README file nor in the releases view.

Maybe have a link to https://console.redhat.com/openshift/downloads ?

**Comment by fidel-ruiz** [comment]
@aliok I was looking for the same in this repo, couldn't find it either

You can probably check https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/
