### ISSUE TITLE
"oc rollout status" allow only one resource type

### ISSUE THREAD

**Issue by R-Studio** [openshift/oc#1279]
## Issue
The command `oc rollout status` allow only one resource type to get the rollout state. 
Whereas with `kubectl` you can run the command for multiple resource types (deployments, daemonsets, statefulsets).

## How to reproduce the issue?
- Run `oc rollout status deployments,daemonsets,statefulsets`
- The following error occurs: `error: you may only specify a single resource type`

## What I expect
- You can run `oc rollout status` against multiple resource types without errors (like with kubectl).

**Comment by ardaguclu** [comment]
They are using the same code base. Could you please compare the versions of `oc` and `kubectl`?

**Comment by R-Studio** [comment]
> They are using the same code base. Could you please compare the versions of `oc` and `kubectl`?

I was really sure that with `kubectl` I was possible to do that, but unfortunately with the current version installed I get the same error message. _(I don't know which version I had installed before.)_
I close this because with the current version of `kubectl` it is not possible to achive this too.
