### ISSUE TITLE
Implement conscious language into the documentation for "oc adm prune groups"

### ISSUE THREAD

**Issue by tonejito** [openshift/oc#1303]
The command line options of the `oc adm prune groups` command still have the **whitelist** / **blacklist** terms. Red Hat has committed to apply changes in order to eliminate the use of these terms in the docummentation [1] [2].

- https://docs.openshift.com/container-platform/4.11/cli_reference/openshift_cli/administrator-cli-commands.html#oc-adm-prune-groups

```
# Prune all orphaned groups except the ones from the blacklist file
oc adm prune groups --blacklist=/path/to/blacklist.txt --sync-config=/path/to/ldap-sync-config.yaml --confirm
```

```
# Prune all orphaned groups from a list of specific groups specified in a whitelist file
oc adm prune groups --whitelist=/path/to/whitelist.txt --sync-config=/path/to/ldap-sync-config.yaml --confirm
```

References:

> [1] https://www.redhat.com/en/blog/update-red-hats-conscious-language-efforts

> [2] https://www.redhat.com/en/blog/making-open-source-more-inclusive-eradicating-problematic-language

**Comment by tonejito** [comment]
XREF: https://chat.google.com/room/AAAAagA7kdc/hmBi50MOT5o

**Comment by ecrookshanks-rh** [comment]
There is a separate "openshift-docs" repository where all the documentation for OpenShift is held.  This is also a GitHub folder and this issue is probably better opened/addressed there.  Or at least duplicated on that site.  It can either be done via a submitted ticket or by cloning the repository and then using the PR mechanism for the entire docs site.

**Comment by tonejito** [comment]
Issue #1303 moved to the `openshift-docs` repository:

- https://github.com/openshift/openshift-docs/issues/54883

**Comment by tonejito** [comment]
I was asked to reopen this issue

- https://github.com/openshift/openshift-docs/issues/54883#issuecomment-1426103025

> [kalexand-rh](https://github.com/kalexand-rh) commented on [`openshift/openshift-docs`](https://github.com/openshift/openshift-docs/issues/54883#issuecomment-1426103025)
> This content is generated from source. Please reopen your issue in `openshift/oc`.
> After the issue is fixed in source, the next time we regenerate the CLI docs, the change will be implemented.

**Comment by ecrookshanks-rh** [comment]
Would this be a 2-phase "fix"?  First would be to implement new options (--allowlist and --denylist) and simply put deprecation warnings for the old options?  And then after a period of time remove the old options?

**Comment by tonejito** [comment]
> _Would this be a 2-phase "fix"? First would be to implement new options (--allowlist and --denylist) and simply put deprecation warnings for the old options? And then after a period of time remove the old options?_

Yeah, whatever works for you is OK. I just pointed this out because I'm working on a training material about OpenShift and I came across this while researching the topics.

**Comment by tonejito** [comment]
I'm not sure if  ecrookshanks-rh and/or kalexand-rh have this on their radar.

This issue on `openshift-docs` is related:

- https://github.com/openshift/openshift-docs/issues/54883#issuecomment-1426103025

On July 15, 2023 2:31:07 AM CST, OpenShift Bot ***@***.***> wrote:
>Stale issues rot after 30d of inactivity.
>
>Mark the issue as fresh by commenting `/remove-lifecycle rotten`.
>Rotten issues close after an additional 30d of inactivity.
>Exclude this issue from closing by commenting `/lifecycle frozen`.
>
>If this issue is safe to close now please do so with `/close`.
>
>/lifecycle rotten
>/remove-lifecycle stale
>

--
  Andrés Hernández
