### ISSUE TITLE
Using existing namespace for must-gather is marked as experimental

### ISSUE THREAD

**Issue by pgodowski** [openshift/oc#1398]
I am using for quite some time the

```
oc adm must-gather --image=<my-custom-image> --run-namespace=<my-namespace>
```

and haven't found any issues with that. Is there any specific reason why `--run-namespace` is marked as hidden and experimental/not supported?

The primary reason why I am interested in using this option is to avoid cluster admin permissions to collect the must-gather data with my custom must-gather image. I think that creating a new namespace on the fly has in the large enterprises significant side effects, esp. when the process of creating the (short-lived) namespace is a problem, requiring change management process.
So, my motivation is pretty much similar / same to the one mentioned in https://github.com/openshift/oc/pull/1080#issue-1154182836

I am wondering whether some conversation could take place to discuss this request.

**Comment by ardaguclu** [comment]
Thanks for opening this issue.

It is not experimental anymore after this https://github.com/openshift/oc/pull/1313 was merged.

**Comment by pgodowski** [comment]
Thank you! I am assuming this will be part of OCP 4.13 release, correct?

**Comment by ardaguclu** [comment]
> Thank you! I am assuming this will be part of OCP 4.13 release, correct?

Yes @pgodowski you are correct. I'm closing this issue, if you don't mind.

/close
