### ISSUE TITLE
openshift-cli 4.13.15 release artifact is the same as 4.13.14

### ISSUE THREAD

**Issue by chenrui333** [openshift/oc#1587]
👋 it looks like the release artifacts for both 4.13.15 and 4.13.14 are the same, raise this issue to confirm if that is intentional.

relates to https://github.com/Homebrew/homebrew-core/pull/152102

**Comment by ardaguclu** [comment]
That would also mean that there is no change in oc but new version is released due to some changes in other components. So that this may not be an issue and can be considered valid.

**Comment by chenrui333** [comment]
make sense, thanks @ardaguclu!
