### ISSUE TITLE
Warn when there are multiple shorthands for different CRDs

### ISSUE THREAD

**Issue by kgibm** [openshift/oc#1606]
I didn't realize that my cluster had two shorthands for different CRDs:

```
% oc get crd | grep -F kafkas   
kafkas.eventstreams.ibm.com                                       2022-09-13T03:58:13Z
kafkas.kafka.strimzi.io                                           2023-05-30T17:46:28Z
```

So just using `kafka` was ambiguous and returned 0 results because it was defaulting to the first CRD.

Adding the fully qualified name worked; however, `oc` was confusing in that I had no idea I was using the "wrong" shorthand.

I suggest that `oc` either fails when there are multiple, overloaded shorthands, or prints a warning when it defaults to one of them.

**Comment by ardaguclu** [comment]
This is completed with https://github.com/kubernetes/kubernetes/pull/117668 and in oc 4.16 version, we will get these warnings. I'd prefer closing this as completed.

**Comment by kgibm** [comment]
Thanks!
