### ISSUE TITLE
`oc logout` should not prompt for username and password when logged out

### ISSUE THREAD

**Issue by datho7561** [openshift/oc#1615]
If I run `oc logout` when the current kube context is set to an OpenShift cluster but I'm logged out, `oc` prompts for a username and password.

The use case is [the integration test suite for vscode-openshift-tools](https://github.com/redhat-developer/vscode-openshift-tools/blob/main/test/integration/ocWrapper.test.ts#L27). We are using `oc` to log in and out of the OpenShift cluster. In the integration tests, we call `oc logout` at the beginning of the test suite regardless of if the user is logged in or not, in order to be robust and handle the case that the developer was logged in when launching the test suite.

Version information:

Client Version: 4.14.3
Kustomize Version: v5.0.1
Kubernetes Version: v1.26.6+73ac56

**Comment by ardaguclu** [comment]
Patch has been merged and issue should be resolved. I'm closing;

/close
