### ISSUE TITLE
Support opening OCP console in the browser

### ISSUE THREAD

**Issue by fxierh** [openshift/oc#1668]
It would be nice if we could open the OCP console in the browser with a single command. 

For this we could consider adding an option like `--open-console` to `oc whoami` or introducing a new subcommand like `oc console ....`.

**Comment by fxierh** [comment]
If this seems reasonable, I'd be happy to open a PR for it.

**Comment by fxierh** [comment]
cc. @ardaguclu

**Comment by ardaguclu** [comment]
I'm not sure that it is a good idea if we automatically open a browser in terms of usability. But printing the console url in _somewhere_ for users easier access might be debatable. 
* Do normal users (not admins) have permissions to GET console url from API server? - if not exposing a flag for only a set of privileges users would not be a good idea
* Can we assume that every OCP cluster has console functionality? - if not exposing a flag for an optional functionality would not be a good idea

**Comment by fxierh** [comment]
Looks like all authenticated users have access to the console URL:
```shell
$ oc get rolebinding -n openshift-config-managed console-public -o wide
NAME             ROLE                  AGE   USERS   GROUPS                 SERVICEACCOUNTS
console-public   Role/console-public   17h           system:authenticated

$ oc get role console-public -n openshift-config-managed -o jsonpath='{.rules}' | jq
[
  {
    "apiGroups": [
      ""
    ],
    "resourceNames": [
      "console-public"
    ],
    "resources": [
      "configmaps"
    ],
    "verbs": [
      "get"
    ]
  }
]

$ oc get cm -n openshift-config-managed console-public -o jsonpath='{.data.consoleURL}'
https://console-openshift-console.apps.fxie-flexy-4.qe.devcluster.openshift.com
```

On the other hand `console` has become an optional capability:
```shell
fxie-mac:cloud-credential-operator fxie$ oc get clusterversion version -o jsonpath='{.status.capabilities.knownCapabilities}' | jq
[
  "Build",
  "CSISnapshot",
  "CloudCredential",
  "Console",
  "DeploymentConfig",
  "ImageRegistry",
  "Insights",
  "MachineAPI",
  "NodeTuning",
  "OperatorLifecycleManager",
  "Storage",
  "baremetal",
  "marketplace",
  "openshift-samples"
]
``` 
so not all OCP clusters has console.

**Comment by fxierh** [comment]
Okay, it looks like we can use e.g. `open $(oc whoami --show-console)` (MacOS) to open the console directly. I guess this should be good enough for us for now.
