### ISSUE TITLE
Add sos package to the tools image

### ISSUE THREAD

**Issue by nekop** [openshift/oc#1675]
Currently we have to use separated image support-tools to collect sosreport and it makes some difficulties when troubleshooting and docs effort. I think it's better to ship the sos command in this image and it makes things simpler.

By incorporating sos command to the tools image:

1. No longer need to mirror extra image support-tools for restricted network env
2. Most troubleshooting command is available in the single tools image (currently sos is only missing piece), great UX
3. The tools image will get a bit larger size due to new package, sos

**Comment by nekop** [comment]
Related:

- https://github.com/containers/toolbox/issues/689
- https://issues.redhat.com/browse/COS-865

**Comment by ardaguclu** [comment]
This was completed by https://github.com/openshift/oc/pull/1704;
/close
