### ISSUE TITLE
Implement oc adm policy why-can for RBAC scan usecases

### ISSUE THREAD

**Issue by Acedus** [openshift/oc#1769]
Hi, couldn't find a contribution format so instead I'll be using k8s'.

### What would you like to be added?

Add a new admin command `why-can` that given positional arguments `[verb] [resource] [identity]` prints a list of RBs/CRBs that grant the specified identity the specified verb on the specified resource. 

### Why is this needed?

Similarly to the existing `who-can`, RBAC in large multi-tenant clusters has a tendency to grow out of control, leaving admins to figure out which RBs and CRBs provide certain permissions to users as exercise. The `why-can` command trivializes that and allows admins to elucidate such concerns with ease.

Implementation wise it should be very similar to the current `who-can` implementation and I don't mind creating a PR for it.

**Comment by Acedus** [comment]
Feature already being worked on by another member of the community, closed.

**Comment by doronkg** [comment]
@Acedus and I began working on this, we'll provide updates on the progress.

**Comment by ardaguclu** [comment]
Thank you for opening this issue. If there isn't any commands in neither kubectl nor oc. I'd recommend first opening issue in kubectl to verify whether it is requested feature or not before investing time and effort. I'm closing this in oc as the primary source of such command should be in kubectl first.

/close
