### ISSUE TITLE
Validation prevents mirroring release to ipv6 registry

### ISSUE THREAD

**Issue by hardys** [openshift/oc#239]
When attempting to use `oc adm release mirror` in an environment where the local registry is only listening on ipv6, it seems there is some validation which prevents using that address in the `--to` location:
```
$ oc adm release mirror --insecure=true -a combined-pullsecret--O2zxxDYRKZ --from registry.svc.ci.openshift.org/ipv6/release:4.3.0-0.nightly-2019-12-20-152137-ipv6.1 --to-release-image fd2e:6f44:5dd8:c956:0:0:0:1:5000/localimages/local-release-image:4.3.0-0.nightly-2019-12-20-152137-ipv6.1 --to [fd2e:6f44:5dd8:c956:0:0:0:1]:5000/localimages/local-release-image
error: --to must be a valid image repository: "[fd2e:6f44:5dd8:c956:0:0:0:1]:5000/localimages/local-release-image" is not a valid image reference: invalid reference format
```

A similar issue exists if you use the IP in the `--to-release-image` pullspec - replacing the IP with a hostname hard-coded in /etc/hosts appears to work around the issue.

Can this validation be relaxed to allow for ipv6 addresses?

**Comment by russellb** [comment]
IPv6 may just not be supported at all, but I did spot this:

```
-to-release-image fd2e:6f44:5dd8:c956:0:0:0:1:5000/localimages/local-release-image:4.3.0-0.nightly-2019-12-20-152137-ipv6.1
```

Square brackets need to be added around the IPv6 address to separate it from the port number.

**Comment by russellb** [comment]
This PR reminded me of a discussion I had here: https://github.com/openshift-metal3/dev-scripts/pull/871

where @adambkaplan was saying that IPv6 addresses are not allowed in a pull spec.  It sounds like using a hostname is the right thing to do instead.

**Comment by adambkaplan** [comment]
yep - @dmage first brought this to my attention. Use a hostname

**Comment by hardys** [comment]
So it seems this may be deliberate ref https://github.com/openshift/openshift-controller-manager/pull/52 ?

**Comment by hardys** [comment]
Ok, seems weird that we allow ipv4 addresses but not ipv6, but I'll rework to use a hostname instead, thanks!
