### ISSUE TITLE
RFC: oc debug: detect node has been accessed

### ISSUE THREAD

**Issue by runcom** [openshift/oc#265]
This is just an RFC for now as I don't fully know the scope of `oc debug` - what we would need from an MCO perspective is a way to detect that someone has jumped on a node with `oc debug`.
Today we can do that with SSH but `oc debug` effectively defeats our detection (based only on ssh).

I was thinking maybe we can mount a file from the host when the `oc debug` pod runs and the MCO can check that to detect that the node has been accessed.

Again, the above is based upon my little knowledge of this code base but anything in this direction would make the MCO more robust when claiming that a user manually patched the system.

**Comment by runcom** [comment]
@smarterclayton @openshift/openshift-architects wdyt?

**Comment by smarterclayton** [comment]
Audit on the apiserver already tracks all attach and exec sessions, so we should already be covered here.

I'm not sure we have to defend to the same degree from node access via exec - it's not really any different from "run a Daemonset that uses a host path", other than it's more temporary.  The SSH taint is intended to discourage use of SSH AND access to nodes.  We possibly should have debug node display a better warning - I'd actually prefer for us to create our own tools image that is aligned to the cluster (vs the rhel tools one which is not) - if we did that, having that print a MOTD is an option.

**Comment by runcom** [comment]
the rationale behind this is debugging issues where the user swears he did not tweak the system manually but perhaps they had and that led to a misconfiguration/bug report etc etc. I'm not sure how we would be able to cause a support burden otherwise :/ Maybe using some sort of annotation on the node when we notice an exec/debug that the MCO can read or something
