### ISSUE TITLE
oc logs -l does not work

### ISSUE THREAD

**Issue by rhuss** [openshift/oc#365]
`oc logs -l` does not work as supposed:

```
oc logs -l serving.knative.dev/service=event-display -c user-container
error: You must provide one or more resources by argument or filename.
Example resource specifications include:
   '-f rsrc.yaml'
   '--filename=rsrc.json'
   '<resource> <name>'
   '<resource>'
```

this is for `oc`:

```
 oc version
Client Version: 4.3.8
Kubernetes Version: v1.17.4+k3s1
```

but i have the same behaviour also for older `oc`s. With `kubectl` the very same command works without issue.

**Comment by starpit** [comment]
Agreed. To add one more oddity, this works:

```
oc logs -lfoo=bar --all-containers -n default
```

and actually with either no `-n` argument, or `-n default`; however, this does not work:

```
oc logs -lfoo=bar --all-containers -n someOtherNamespace
```

With the only difference being that, in this case, the `-n` namespace is not `default`. We have verified that `sameOtherNamespace` has pods that satisfy that label selector. in case it helps, specficially in our tests, someOtherNamespace is "23ca40ab-ef10-4ce0-a452-60857da77f94-kui"

We have this problem with both oc `v4.1.0+b4261e0`, and 4.3.3.

**Comment by rhuss** [comment]
Haven't verified this, but haven't seen a fix for this yet.

**Comment by rhuss** [comment]
Just checked with oc 4.7.0, works now like expected.
