### ISSUE TITLE
oc build from `master` sources gives outdated version number

### ISSUE THREAD

**Issue by c3d** [openshift/oc#416]
Built `oc` from master source commit f415627b3a8df305c4dd0ada0b4bc1271846a777, which I expected to be a development branch. Seems to be sync'ed with `release-4.7` branch:

```
commit f415627b3a8df305c4dd0ada0b4bc1271846a777 (HEAD -> master, origin/release-4.7, origin/release-4.6, origin/release-4.5, origin/master, origin/HEAD)
Merge: 361c30813 b27b4901a
Author: OpenShift Merge Robot <openshift-merge-robot@users.noreply.github.com>
Date:   Thu May 7 21:37:23 2020 +0200

    Merge pull request #409 from soltysh/bug1826230
    
    Bug 1826230: bring missing fixes to oc
```

However, running `oc version` gives something a bit nonsensical:

```
% ./oc version
Client Version: v4.2.0-alpha.0-571-gf415627
Kubernetes Version: v1.18.2
```

Saw the same problem on Fedora 32 and macOS.

**Comment by simonkrenger** [comment]
I am hitting the same issue while trying to update [openshift-cli](https://github.com/Homebrew/homebrew-core/blob/master/Formula/openshift-cli.rb) for Homebrew:

```
$ oc version --client
Client Version: v4.2.0-alpha.0-550-gae3e321
```

https://github.com/openshift/oc/blob/master/pkg/version/version.go#L60 tells us that this likely has to be modified post-compilation.
