### ISSUE TITLE
oc client registry.redhat.io/openshift4/ose-cli:latest is slow due to $HOME not set

### ISSUE THREAD

**Issue by fgiloux** [openshift/oc#474]
When running oc commands in the ose-cli image it makes a difference whether the container is run by a privileged user or not. With a privileged user HOME is set as /root whereas with an unprivileged user HOME is / and not writable.
This induces many errors that can be seen by bumping the log level, for instance:
I0623 08:08:54.218291       7 cached_discovery.go:87] failed to write cache to /.kube/cache/discovery/172.30.0.1_443/machine.openshift.io/v1beta1/serverresources.json due to mkdir /.kube: permission denied
This is happening all the time when the container is started with the default SA.

As cluster admin:
$ oc run -it --image=registry.redhat.io/openshift4/ose-cli:latest bash
If you don't see a command prompt, try pressing enter.
[root@bash /]# id
uid=0(root) gid=0(root) groups=0(root)
[root@bash /]# echo $HOME
/root

As normal user
$ oc run -it --image=registry.redhat.io/openshift4/ose-cli:latest bash --as=frederic
If you don't see a command prompt, try pressing enter.
bash-4.2$ id
uid=1000600000(1000600000) gid=0(root) groups=0(root),1000600000
bash-4.2$ echo $HOME
/

I am proposing to add the following to oc/images/cli/Dockerfile.rhel
ENV HOME /tmp/home
RUN mkdir $HOME && chmod 777 $HOME

This would solve the issue. If you find that reasonable I can open a PR.

**Comment by soltysh** [comment]
I don't think we need both this issue and https://bugzilla.redhat.com/show_bug.cgi?id=1850331 so I'm closing this one in favor of that BZ.
