### ISSUE TITLE
`oc version` format inconsistent between external download and console download

### ISSUE THREAD

**Issue by chrisbygrave** [openshift/oc#556]
If I download an oc binary [here](https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest-4.5/openshift-client-mac-4.5.7.tar.gz) and run `oc version` I get:
```
Client Version: 4.5.7
Server Version: 4.5.7
Kubernetes Version: v1.18.3+2cf11e2
```

However if I pull the binary from the OpenShift console of a 4.5.7 server and run `oc version` I see:
```
Client Version: openshift-clients-4.5.0-202006231303.p0-4-gb66f2d3a6
Server Version: 4.5.7
Kubernetes Version: v1.18.3+2cf11e2
```

This makes scripting with `oc` more complicated. What's the reason for a non-semver client version field in the binary downloaded from the OpenShift console?

**Comment by fckbo** [comment]
Hello, 
looking at the code here: https://github.com/openshift/oc/blob/master/pkg/version/version.go and at this https://github.com/openshift/oc/pull/88, it looks that this was actually done intentionally.

You might want to use 
```
oc version -o yaml

on my system, it gives this:
```
oc version -o yaml
clientVersion:
  buildDate: "2020-07-13T19:36:22Z"
  compiler: gc
  gitCommit: 592b165660fbf31430b78575e311837d6e73514f
  gitTreeState: clean
  gitVersion: openshift-clients-4.6.0-202005210021-30-g592b16566
  goVersion: go1.13.4
  major: ""
  minor: ""
  platform: darwin/amd64
releaseClientVersion: 4.5.2
```
