### ISSUE TITLE
make oc fails if default sh is not bash

### ISSUE THREAD

**Issue by aceeric** [openshift/oc#561]
```
$ go version
go version go1.15.2 linux/amd64

$ make go
/bin/sh: 1: set: Illegal option -o pipefail
vendor/github.com/openshift/build-machinery-go/make/targets/golang/../../lib/golang.mk:22: *** `go` is required
with minimal version "1.14.4", detected version "1.15.2". You can override this check by using `make
GO_REQUIRED_MIN_VERSION:=`.
Stop.

$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"

$ file `which sh`
/bin/sh: symbolic link to dash

$ apt-cache policy dash
dash:
  Installed: 0.5.8-2.10
  Candidate: 0.5.8-2.10
  Version table:
 *** 0.5.8-2.10 500
        500 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
```

The first manifestation of the error is in: `vendor/github.com/openshift/build-machinery-go/make/lib/version.mk`. This line of code:

```
$(strip $(filter $(2),$(firstword $(shell set -euo pipefail && printf '%s\n%s' '$(1)' '$(2)' | sort -V -r -b))))
```

The issue:

```
$ echo $SHELL
/bin/bash
$ sh
$ set -euo pipefail 
dash: 1: set: Illegal option -o pipefail
```

Adding this as line one of `Makefile` resolves it:
```
export SHELL := $(shell which bash)
```

In summary - if the Make file requires bash then it should explicitly define it. It seems this would make the Make file more portable.

**Comment by StefThomas** [comment]
Same here :

$ make oc
/bin/sh: 1: set: Illegal option -o pipefail
vendor/github.com/openshift/build-machinery-go/make/targets/golang/../../lib/golang.mk:22: *** `go` is required with minimal version "1.14.4", detected version "1.15.8". You can override this check by using `make GO_REQUIRED_MIN_VERSION:=`. Arrêt.

My /bin/sh is a symlink to /bin/dash (default in Debian (and maybe Ubuntu)). Making it a symlink to /bin/bash instead solves the issue.

**Comment by dupdrop** [comment]
This is still a problem. OP's solution of setting the shell explicitly fixes it.
