### ISSUE TITLE
Rest login from old server

### ISSUE THREAD

**Issue by yehia67** [openshift/oc#564]
Hello,
I am new at using  OC. I just tried to install OpenShift on a VPC then I  connected to the VPC using 
```
oc login --token=<token> --server=https://<server>:6443
```
Now I just closed the VPC before logout from the terminal. Now I am trying to use oc but I got this error

```
oc logout
Unable to connect to the server: dial tcp: lookup api.blockchain.openshift.valoro.xyz on 127.0.0.53:53: no such host
```
If I tried to log in using another server
```
oc login
error: dial tcp: lookup api.blockchain.openshift.valoro.xyz on 127.0.0.53:53: no such host - verify you have provided the correct host and port and that the server is currently running.
```
How to remove the old server from my local command?
Thanks in Advance.

**Comment by fckbo** [comment]
Hi,

You should have a [https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/#merging-kubeconfig-files](kubeconfig) file, (e.g ~/.kube/config file) where this is stored. 

You can update this file or you can use `oc config <subcommand> [flags]`. Use `oc help config`to know more.

e.g
```
oc config get-clusters
oc config get-contexts
oc config delete-cluster <clustername> or oc config delete-context < contextname> depending what you want to do
```
Hope this helps.

**Comment by yehia67** [comment]
Okay, Thanks!
