### ISSUE TITLE
Release oc binary for ARM64

### ISSUE THREAD

**Issue by odidev** [openshift/oc#614]
I am working on the project ‘kui’ for adding ARM64 support, and kui uses ‘oc’ binary. Kui installs oc by downloading tar.gz from here <https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.5.14/> and extracting ‘oc’. 
I have checked that these binaries are specific to x86_64. 

Project ‘openshift/oc’ supports ARM64 and I have generated an ARM64 ‘oc’ binary on a local ARM64 machine. Followed the below steps
~~~
$ apt-get install -y libkrb5-dev
$ Installed go 1.15.2 for arm64
$ git clone  https://github.com/openshift/oc.git
$ cd oc && make oc
~~~
I have verified binary is of aarch64 platform with below command
~~~
$ file oc
oc: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, BuildID[sha1]=8d775f8a9c28964861f5fc6a4a792641b0061e58, for GNU/Linux 3.7.0, stripped
~~~ 

It would be really helpful if the ‘oc’ binary becomes available for ARM64.

**Comment by EKoetsjarjan** [comment]
Hi I'm looking to run oc command directly from a mobile platform such as Android or iPhone,
do you managed to test this build? and do you think this could also work on mobiles?
