### ISSUE TITLE
Kext Stall: X86PlatformPlugin and missing AGPM boot very slow

### ISSUE THREAD

**Issue by thainhan07103** [openshift/oc#643]
OC 0.6.3 work geart 10.15.7 and Big Sur beta 6
After update Big Sur my device boot Kext stall: X86PlatformPlugin
stuck Kext stall: X86PlatformPlugin about 3-5 minutes after that macOS boot successful
I create ssdt and CPU Frends but no helpful

**Comment by josineiaraujo** [comment]
> OC 0.6.3 work geart 10.15.7 e Big Sur beta 6
> Após a atualização Big Sur, meu dispositivo de inicialização Kext stall: X86PlatformPlugin
> travou Kext stall: X86PlatformPlugin cerca de 3-5 minutos após a inicialização do macOS bem-sucedida
> eu crio ssdt e CPU Frends, mas não ajudou

I have the same problem, how did you manage to solve it?
