### ISSUE TITLE
Built binary will report wrong version when executing oc version

### ISSUE THREAD

**Issue by MohsenRahimi** [openshift/oc#740]
I checked out the release tag openshift-clients-4.6.0-202006250705.p0
after build, 'oc version' is reporting 4.2.

I dig a little bit and found out in github.com/openshift/build-machinery-go/make/lib/golang.mk line 53

SOURCE_GIT_TAG ?=$(shell git describe --long --tags --abbrev=7 --match 'v[0-9]*' || echo 'v0.0.0-unknown')

--match 'v[0-9]*' causing this issue, as recent tags start with 'openshift-clients-' not 'v'

I built the binary on MacOs Big Sur

**Comment by jwhb** [comment]
This is expected: https://github.com/openshift/oc/issues/774#issuecomment-849736677

**Comment by soltysh** [comment]
This is expected, but I'll be looking into how we can improve that situation for publishing homebrew and chocolatey, see #774.
/close
