### ISSUE TITLE
oc adm max-components=2

### ISSUE THREAD

**Issue by damobrisbane** [openshift/oc#758]
It is hard to debug and unintuitive to understand why image paths are getting shortened because of this parameter. An image push is a straight forward translation: <repository><image_path><version>, this mangles the <image_path> number of sub-components. 

Even if there are good reasons for limiting number image path components, is that not an external issue and this is a workaround? The point is, when hitting problems, looking into the oc adm command as source is not always obvious and the mangling itself complicates other configurations because image paths are being transformed in a sometimes complicated way.

**Comment by monkey1016** [comment]
I've found that you can disable the path component limits with `--max-components=0`
