### ISSUE TITLE
In version 4.7 of oc, a GIT SSH repository url is changed on BuildConfigs and SSH authentication secrets are not correctly attached

### ISSUE THREAD

**Issue by PiotrSpikowski** [openshift/oc#822]
#### Description
In all oc 4.7 client versions, `new-app` and `new-build` commands (and possibly others) change a GIT SSH url of a `BuildConfig` and do not attach related SSH authentication secrets. As a result, a source code build fails because it’s not possible to clone a repository. The issue does not exist in oc 4.6 and possibly in earlier versions.

#### Reproduction
* You have a builder container image and an image stream created for it. E.g. `my-builder-ubi8`
* You have a private GIT repository serving source code to be built via SSH e.g. `ssh://my.private.git:22/tfs/Global/Sample/_git/Sample-Console`
* You have an SSH secret created for your SSH url and linked into a builder account e.g.
  ```bash
  oc create secret generic my-secret --from-file=ssh-privatekey=id_rsa --type=kubernetes.io/ssh-auth
  oc secrets link builder my-secret
  oc annotate secret/my-secret "build.openshift.io/source-secret-match-uri-1=ssh://my.private.git:22/tfs/Global/Sample/_git/Sample-Console"
  ```
* You use one of the commands:
  * the `new-app` command to build your source code with help of a provided image e.g.
  ```bash
  oc new-app my-builder-ubi8~ssh://my.private.git:22/tfs/Global/Sample/_git/Sample-Console --name=sample-app
  ```
  * the `new-build` command to create a build definition e.g.
  ```bash
  oc new-build my-builder-ubi8~ssh://my.private.git:22/tfs/Global/Sample/_git/Sample-Console --name=sample-src-build
  ```
  * other commands creating `BuildConfig`s

#### Results
Builds fail on the git-clone init container:
```bash
Cloning "my.private.git:22/tfs/Global/Sample/_git/Sample-Console "
error: Host key verification failed.
fatal: Could not read from remote repository.
```
* The above fails with oc 4.7. It runs fine with 4.6 and earlier versions. Secrets are correctly defined.

#### Details
* The created `BuildConfig` points at the `my.private.git:22/tfs/Global/Sample/_git/Sample-Console` and not at the `ssh://my.private.git:22/tfs/Global/Sample/_git/Sample-Console` as it was before
* The `my-secret` is not linked (there is no `sourceSecret` on the `BuildConfig`)
* Changing annotation on a secret (by removing `ssh`) does not help. A secret is still not attached into a created `BuildConfig`

#### Expected results
* A created build should run with no issues and a correct secret should be added into its definition (`sourceSecret` on the `BuildConfig`)

#### Workarounds
* Manually add secrets into created `BuildConfig`s or
* Run your commands using the oc 4.6 or
* Use yaml/json resource definition files, do not relay on mentioned commands. Include `ssh://` in your urls

**Comment by gabemontero** [comment]
We are tracking this in https://bugzilla.redhat.com/show_bug.cgi?id=1971332

Where I believe we introduced this via https://bugzilla.redhat.com/show_bug.cgi?id=1884270 with PR https://github.com/openshift/source-to-image/pull/1054 and https://github.com/openshift/oc/pull/610

We'll just have to sort out out to deal with the competing concerns.

/close
