### ISSUE TITLE
Support for `-n` option to specify namespace in `oc rsh` command

### ISSUE THREAD

**Issue by sagar-jadhav** [openshift/oc#901]
- `oc rsh` command doesn't support `-n` option to specify `namespace`.
- Workaround for this is to first switch the `project/namespace` where a particular `Pod` is present using `oc project <project_name>` command  and then run the `oc rsh` command.

**OC version:** v4.2.0-alpha.0-657-g51011e4

**Comment by apoorvajagtap** [comment]
Hello @sagar-jadhav, have you tried the `rsh` via following command?
$ oc -n <namespace> rsh <pod-name>
- I checked this with oc version 4.7.18 and seems to be working as expected.

**Comment by sagar-jadhav** [comment]
Thank you @apoorvajagtap , I'll upgrade the OC CLI to `4.7.18`
