### ISSUE TITLE
Openshift Client is not up to date in homebrew

### ISSUE THREAD

**Issue by chmouel** [openshift/oc#954]
It seems that the homebrew formula refers to the tags : 

https://github.com/Homebrew/homebrew-core/blob/master/Formula/openshift-cli.rb#L9

but there is no  releasetags for 4.8.x in https://github.com/openshift/oc/tags

is it expected? should they use the release branches instead ? https://github.com/openshift/oc/tree/release-4.8

**Comment by Moisan** [comment]
See the discussion here: https://github.com/Homebrew/homebrew-core/pull/90407
> A branch is a moving target, which makes these builds non-reproducible, which we shouldn't have.

Is there any way to add release tags?

**Comment by georgettica** [comment]
@Moisan new tags have been added. working with homebrew to re-enable it

**Comment by georgettica** [comment]
New tags are enabled, so maybe we can close it?
Check the brew issue

**Comment by chmouel** [comment]
👍🏻 closing this as this is fixed now...
