### ISSUE TITLE
`oc` completion not working despite running the required command `oc completion zsh` or saving output to zsh `fpath`

### ISSUE THREAD

**Issue by robbyki** [openshift/oc#968]
Not understanding why my `oc` completion isn't working despite all of my other completions working perfectly in zsh environment. Downloaded the latest binary for `oc` and have it installed in my `/usr/local/bin/` space and then trying the following scenarios with zero luck:
 `source [<oc completion zsh)`  and saving that in `.zshrc` with no success. 
or simply saving the output to my `fpath` custom location along with all of my other completions such as `kubectl` which work fine. 
`oc completion zsh > ~/.oh-my-zsh/completions/_oc`
After running any of the above I still get nothing for tab completion against `oc`.

**Comment by eifrach** [comment]
try to edit `~/.oh-my-zsh/completions/_oc`
and add this change on the top of the file

```console
# compdef _kubectl kubectl
compdef _oc oc
```

i see that the completion doesn't work on mac without this

**Comment by robbyki** [comment]
thank you. This worked when I tried a version different from the binary I originally tried from redhat portal. When I tried `Client Version: 4.7.36` the completion from `fpath` worked finally. Didn't have a chance to look into why the latest version from redhat didn't work.

**Comment by eifrach** [comment]
yes so i see this change was added on the `4.9` release 
i was using the `4.8` without an issue.

https://github.com/openshift/oc/blob/master/contrib/completions/zsh/oc#L2-L4

**Comment by paulbarfuss** [comment]
There are a couple of other workarounds for this, such as downgrading your client for the `oc completion zsh` command, or replacing doing a `s/kubectl/oc/` as a one-liner.

```bash
# Load the oc completion code for zsh[1] into the current shell
source <(oc completion zsh | sed -e 's/kubectl/oc/g')
# Set the oc completion code for zsh[1] to autoload on startup
oc completion zsh | sed -e 's/kubectl/oc/g' > "${fpath[1]}/_oc"
```

**Comment by paulbarfuss** [comment]
@eifrach  It appears https://github.com/openshift/oc/blob/master/contrib/completions/zsh/oc is just a generated file for testing purposes and not a template. The `oc completion` command is just a wrapper for `kubectl completion` so the issue is going to be a change upstream to how this command produces the zsh completions and would not be as simple as fixing the generated file.

It looks like the `compdef kubectl _kubectl` line is now being hardcoded in the upstream `kubectl completion zsh` function:

https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/completion/completion.go#L173

**Comment by eifrach** [comment]
the `kubectl` completion works fine on `zsh` but it appears the add line `compdef kubectl _kubectl` breaks the `oc` completion starting from `release-4.8`

this is my fix

```
# cat ~/.zshrc | grep "oc completion"
source <(oc completion zsh | sed -e 's/compdef _kubectl kubectl/compdef _oc oc/' )
```

**Comment by paulbarfuss** [comment]
Yeah @eifrach and the new way defintely adds the `#compdef` tags properly without any need for the `zshHead`

Updated https://github.com/openshift/oc/pull/989 to remove it and will look into getting it removed upstream if possible.

**Comment by paulbarfuss** [comment]
Linking related upstream issue/PR with possibly a simpler solution that unwrapping the `oc completion` command.

Upstream issue: https://github.com/kubernetes/kubernetes/issues/106968
Upstream PR: https://github.com/kubernetes/kubernetes/pull/106969

It looks like the upstream fix is just waiting on a final approval.
